// Live server test: node tests/server.mjs  (starts server, hits API, cleans up)
import {spawn} from 'node:child_process';import fs from 'node:fs';
const PORT=3101;const delay=ms=>new Promise(r=>setTimeout(r,ms));
const start=()=>spawn('node',['server/server.js'],{env:{...process.env,PORT},cwd:new URL('..',import.meta.url).pathname});
let srv=start();await delay(900);
let pass=0,fail=0;const ok=(n,c)=>{c?pass++:fail++;console.log((c?'PASS ':'FAIL ')+n)};
try{
  const h=await (await fetch(`http://localhost:${PORT}/healthz`)).json();ok('healthz',h.ok===true);
  const s=await fetch(`http://localhost:${PORT}/api/auth/signup`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({u:'tester',e:'t@x.io',p:'long-password-123'})});
  ok('signup 200',s.status===200);
  const s2=await fetch(`http://localhost:${PORT}/api/auth/signup`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({u:'tester',e:'t@x.io',p:'long-password-123'})});
  ok('duplicate 409',s2.status===409);
  const bad=await fetch(`http://localhost:${PORT}/api/auth/signup`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({u:'x',e:'x@x.io',p:'short'})});
  ok('short password 400',bad.status===400);
  const l=await (await fetch(`http://localhost:${PORT}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:'tester',p:'long-password-123'})})).json();
  ok('login token',!!l.token);
  const l2=await fetch(`http://localhost:${PORT}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:'tester',p:'nope-nope-nope!'})});
  ok('wrong pass 401',l2.status===401);
  const sec=await fetch(`http://localhost:${PORT}/`);ok('CSP header',!!sec.headers.get('content-security-policy'));
  ok('HSTS header',!!sec.headers.get('strict-transport-security'));
  const ai=await fetch(`http://localhost:${PORT}/api/ai`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:'hi'})});
  ok('ai without key 501',ai.status===501);
  // phase 2: restart to reset in-memory rate counters (data/ persists)
  srv.kill();await delay(400);srv=start();await delay(900);
  const B=`http://localhost:${PORT}`;
  const H=t=>({Authorization:'Bearer '+t,'Content-Type':'application/json'});
  const st=await (await fetch(B+'/api/auth/totp/setup',{method:'POST',headers:H(l.token)})).json();
  ok('totp setup secret',!!st.secret&&!!st.uri);
  const tv1=await fetch(B+'/api/auth/totp/verify',{method:'POST',headers:H(l.token),body:JSON.stringify({code:'000000'})});
  ok('totp bad code 401',tv1.status===401);
  const {totp}=await import('../js/totp.js');
  const tv2=await fetch(B+'/api/auth/totp/verify',{method:'POST',headers:H(l.token),body:JSON.stringify({code:totp(st.secret)})});
  ok('totp good code 200',(await tv2.json()).enabled===true);
  const lNoCode=await fetch(B+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:'tester',p:'long-password-123'})});
  ok('server login without totp 401',lNoCode.status===401);
  const lCode=await (await fetch(B+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:'tester',p:'long-password-123',code:totp(st.secret)})})).json();
  ok('server login with totp',!!lCode.token);
  const T=lCode.token;
  const g0=await (await fetch(B+'/api/sync',{headers:H(T)})).json();ok('sync empty rev0',g0.rev===0&&g0.blob===null);
  const gU=await fetch(B+'/api/sync');ok('sync unauth 401',gU.status===401);
  const blob={salt:'eA==',iv:'eQ==',ct:'ZmFrZS1ibG9i'};
  const p1=await (await fetch(B+'/api/sync',{method:'POST',headers:H(T),body:JSON.stringify({base:0,blob})})).json();
  ok('sync push rev1',p1.rev===1);
  const pStale=await fetch(B+'/api/sync',{method:'POST',headers:H(T),body:JSON.stringify({base:0,blob})});
  ok('sync stale 409',pStale.status===409);
  const g1=await (await fetch(B+'/api/sync',{headers:H(T)})).json();
  ok('sync pull blob opaque',g1.rev===1&&g1.blob.ct==='ZmFrZS1ibG9i');
  const lo=await fetch(B+'/api/auth/logout',{method:'POST',headers:H(T)});
  ok('logout 200',(await lo.json()).ok===true);
  const gDead=await fetch(B+'/api/sync',{headers:H(T)});
  ok('revoked token 401',gDead.status===401);
  const dpath=new URL('../server/data/tokens.json',import.meta.url).pathname;
  const all=JSON.parse(fs.readFileSync(dpath,'utf8'));
  all.push({id:'oldtok',user:'tester',at:new Date(Date.now()-25*3600*1000).toISOString()});
  fs.writeFileSync(dpath,JSON.stringify(all));
  const gOld=await fetch(B+'/api/sync',{headers:H('oldtok')});
  ok('expired token 401',gOld.status===401);
}catch(e){ok('no exception: '+e.message,false)}
srv.kill();fs.rmSync(new URL('../server/data',import.meta.url).pathname,{recursive:true,force:true});
console.log(`\n${pass} passed, ${fail} failed`);process.exit(fail?1:0);
