// Smoke tests: node tests/smoke.mjs  (run from abrash-os/)
const mem={};global.localStorage={getItem:k=>mem[k]??null,setItem:(k,v)=>mem[k]=String(v),removeItem:k=>delete mem[k],clear:()=>{for(const k in mem)delete mem[k]}};
Object.defineProperty(globalThis,'navigator',{value:{userAgent:'smoke',language:'ar'},configurable:true});global.screen={width:1,height:1};
let pass=0,fail=0;const ok=(n,c)=>{c?pass++:fail++;console.log((c?'PASS ':'FAIL ')+n)};
const core=await import('../js/core.js');
ok('escapeHTML blocks script',core.escapeHTML('<script>alert(1)</script>')==='&lt;script&gt;alert(1)&lt;/script&gt;');
ok('mdLite escapes + bolds',core.mdLite('**x** <b>').includes('<b>x</b>')&&!core.mdLite('<b>').includes('<b>'));
ok('uid unique',core.uid()!==core.uid());
const {Store,seedDefaults}=await import('../js/store.js');seedDefaults();
const n=Store.push('notes',{title:'مشروع الأمن السيبراني',body:'خطة',tags:['sec']});
ok('store push/get',Store.col('notes').some(x=>x.id===n.id));
Store.update('notes',n.id,{title:'معدل'});ok('store update',Store.col('notes').find(x=>x.id===n.id).title==='معدل');
const {globalSearch,parseNatural}=await import('../js/modules/search.js');
ok('globalSearch finds note',globalSearch('معدل').some(r=>r.title==='معدل'));
const r=parseNatural('أنشئ مشروع باسم X');ok('natural create-project',r.msg?.includes('X')&&Store.col('projects').some(p=>p.name==='X'));
const r2=parseNatural('ذكرني غدًا بمراجعة المشروع');ok('natural remind',Store.col('tasks').some(x=>x.title.includes('مراجعة المشروع')));
const {hashPass,verifyPass}=await import('../js/crypto.js');
const h=await hashPass('correct-horse-12+');ok('pbkdf2 verify ok',await verifyPass('correct-horse-12+',h.salt,h.hash));
ok('pbkdf2 wrong rejects',!(await verifyPass('wrong',h.salt,h.hash)));
ok('noteToMarkdown escapes nothing raw',core.noteToMarkdown({title:'<x>',body:'**b**',tags:['a']}).startsWith('# <x>'));
const seed=await import('../js/modules/seed.js');
['notes','projects','tasks','knowledge','goals','ideas','events','files'].forEach(k=>Store.set(k,[]));
ok('seed empty at first',seed.isEmpty());
ok('seedDemo fills workspace',seed.seedDemo()===true&&Store.col('projects').length>=2&&Store.col('tasks').length>=5);
ok('seedDemo idempotent',seed.seedDemo()===false);
const totp=await import('../js/totp.js');
const RS='GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ';
ok('totp RFC vector',totp.totp(RS,59e3)==='287082');
ok('totp rejects wrong',!totp.verifyTotp(RS,'000000',59e3));
const {Auth}=await import('../js/auth.js');
await Auth.signup('u2','u2@x.io','long-password-123');
await Auth.login('u2','long-password-123',null);ok('login no-totp ok',!!Store.get('session',null));
const {secret}=Auth.totpSetup();ok('totp setup secret',secret.length>=16);
ok('totp enable rejects bad',Auth.totpEnable(secret,'000000')===false);
ok('totp enable accepts live',Auth.totpEnable(secret,totp.totp(secret))===true);
let needCode=false;try{await Auth.login('u2','long-password-123',null)}catch(e){needCode=/TOTP/.test(e.message)}
ok('login without code rejected',needCode);Auth.logout();
await Auth.login('u2','long-password-123',totp.totp(secret));ok('login with code ok',!!Store.get('session',null));Auth.logout();
ok('checkPass logged-out false',await Auth.checkPass('long-password-123')===false); // logged out → false
await Auth.login('u2','long-password-123',totp.totp(secret));
ok('checkPass live',await Auth.checkPass('long-password-123')===true);
ok('checkPass wrong',await Auth.checkPass('nope-nope-nope!')===false);Auth.logout();
const sync=await import('../js/modules/sync.js');
Store.set('notes',[{id:'c1',title:'A',body:'1',updatedAt:'2024-01-01T00:00:00.000Z'}]);
Store.set('syncBase',sync.snap());
Store.update('notes','c1',{title:'mine',updatedAt:'2024-02-01T00:00:00.000Z'});
const remote={notes:[{id:'c1',title:'theirs',body:'1',updatedAt:'2024-03-01T00:00:00.000Z'}]};
const conf=sync.findConflicts(remote);
ok('conflict detected',conf.length===1&&conf[0].title==='theirs');
sync.resolveConflict(conf[0],'mine');
ok('resolve keeps mine',Store.col('notes').find(x=>x.id==='c1').title==='mine');
ok('no conflict after resolve',sync.findConflicts(remote).length===0);
const n2=sync.mergeAll({notes:[{id:'c2',title:'new',updatedAt:'2024-05-01T00:00:00.000Z'}]});
ok('merge adds remote-only',n2===1&&Store.col('notes').some(x=>x.id==='c2'));
const rec=await import('../js/modules/recurring.js');
Store.set('tasks',[{id:'tpl',title:'رياضة',priority:'P1',recurring:'daily',nextDue:'2024-01-01',updatedAt:'2024-01-01T00:00:00.000Z'}]);
ok('recurring spawns missed days',rec.runRecurring('2024-01-03')===3);
ok('recurring advances nextDue',Store.col('tasks').find(x=>x.id==='tpl').nextDue==='2024-01-04');
ok('recurring idempotent same day',rec.runRecurring('2024-01-03')===0);
const ret=await import('../js/modules/retention.js');
Store.set('notes',[{id:'old',title:'x',deleted:true,updatedAt:'2020-01-01T00:00:00.000Z'},{id:'keep',title:'y',updatedAt:'2024-06-01T00:00:00.000Z'}]);
Store.set('audits',[{id:'a1',action:'x',at:'2020-01-01T00:00:00.000Z'}]);
const ro=ret.applyRetention({retTrash:30,retLogs:30},new Date('2024-06-15T00:00:00Z').getTime());
ok('retention purges trash+logs',ro.trash===1&&ro.logs===1&&!Store.col('notes').some(x=>x.id==='old'));
const {can}=await import('../js/perms.js');
ok('perms owner wipe',can('owner','wipe')===true);
ok('perms viewer read-only',can('viewer','read')===true&&can('viewer','delete')===false&&can('editor','delete')===false&&can('admin','delete')===true);
console.log(`\n${pass} passed, ${fail} failed`);process.exit(fail?1:0);