create extension if not exists pgcrypto, pg_trgm;
create table users(id uuid primary key default gen_random_uuid(), email citext unique not null, username text unique not null, pass_hash text not null, salt text not null, tfa_secret text, role text default 'owner', created_at timestamptz default now());
create table sessions(id uuid primary key default gen_random_uuid(), user_id uuid references users(id) on delete cascade, device text, ua text, ip inet, trusted bool default false, created_at timestamptz default now(), last_seen timestamptz default now(), revoked bool default false);
create table login_attempts(id uuid primary key default gen_random_uuid(), user_id uuid references users(id) on delete cascade, ip inet, ua text, ok bool, at timestamptz default now());create index on login_attempts(user_id, at desc);
create table notes(id uuid primary key default gen_random_uuid(), owner_id uuid references users(id) on delete cascade, title text, body text, type text, folder text, tags text[], fav bool default false, archived bool default false, deleted_at timestamptz, updated_at timestamptz default now());
create index notes_fts on notes using gin(to_tsvector('simple', coalesce(title,'')||' '||coalesce(body,'')));create index on notes(owner_id, updated_at desc);
create table files(id uuid primary key default gen_random_uuid(), owner_id uuid references users(id) on delete cascade, name text, kind text, size int, folder text, tags text[], storage_key text, deleted_at timestamptz, updated_at timestamptz default now());create index on files(owner_id, updated_at desc);
create table projects(id uuid primary key default gen_random_uuid(), owner_id uuid references users(id) on delete cascade, name text, descr text, stage text, priority text, deadline date, budget text, updated_at timestamptz default now());
create table tasks(id uuid primary key default gen_random_uuid(), owner_id uuid references users(id) on delete cascade, project_id uuid references projects(id) on delete set null, title text, priority text, due date, done bool default false, subs jsonb default '[]', updated_at timestamptz default now());
create table vault_items(id uuid primary key default gen_random_uuid(), owner_id uuid references users(id) on delete cascade, nonce bytea, blob bytea, created_at timestamptz default now());
create table knowledge(id uuid primary key default gen_random_uuid(), owner_id uuid references users(id) on delete cascade, title text, body text, cat text, tags text[], src text);
create table events(id uuid primary key default gen_random_uuid(), owner_id uuid references users(id) on delete cascade, title text, date date);
create table goals(id uuid primary key default gen_random_uuid(), owner_id uuid references users(id) on delete cascade, title text, range text, progress int default 0);
create table ideas(id uuid primary key default gen_random_uuid(), owner_id uuid references users(id) on delete cascade, title text, problem text, solution text, audience text, stage text);
create table audits(id uuid primary key default gen_random_uuid(), user_id uuid references users(id) on delete set null, action text, meta jsonb, ip inet, ua text, at timestamptz default now());create index on audits(user_id, at desc);
alter table notes enable row level security;create policy owner_only on notes for all using (owner_id = auth.uid());-- repeat per table
