import {Store} from '../store.js';import {escapeHTML,fmtD,mdLite,download,noteToMarkdown} from '../core.js';import {toast,empty,confirmDlg} from '../ui.js';
const TYPES=['نصية','طويلة','Checklist','جدول','Code','فكرة','يوميات','خاصة','مشروع'];
export const parseLinks=(body)=>{const out=[];const re=/\[\[([^\[\]]{1,80})\]\]/g;let m;while((m=re.exec(body||'')))out.push(m[1].trim());return [...new Set(out)].filter(Boolean)};
export const findBacklinks=(id)=>{const me=Store.col('notes').find(x=>x.id===id);if(!me||!me.title)return [];
  const tag=`[[${me.title}]]`;return Store.col('notes').filter(n=>!n.deleted&&n.id!==id&&(n.body||'').includes(tag))};
export const noteFolders=()=>[...new Set(Store.col('notes').filter(n=>!n.deleted&&n.folder).map(n=>n.folder))];
export function renderNotePreview(body){let h=mdLite(body||'');h=h.replace(/\[\[([^\[\]]{1,80})\]\]/g,(m,t)=>`<a href="#" data-link="${escapeHTML(t.trim())}" class="tag">⛓ ${escapeHTML(t.trim())}</a>`);return h}
export function render(el){let q=Store.get('notesQ',{s:'',f:'all',g:''});
  el.innerHTML=`<div class="between"><h2 style="margin:0">🗒 الملاحظات الذكية</h2><button class="btn primary sm" id="nNew">＋ ملاحظة</button></div>
  <div class="toolbar"><input id="nS" placeholder="بحث…" value="${escapeHTML(q.s)}"><select id="nF"><option value="all">الكل</option>${TYPES.map(x=>`<option ${q.f===x?'selected':''}>${x}</option>`).join('')}<option value="fav" ${q.f==='fav'?'selected':''}>⭐ المفضلة</option><option value="arch" ${q.f==='arch'?'selected':''}>الأرشيف</option><option value="trash" ${q.f==='trash'?'selected':''}>السلة</option></select><select id="nG"><option value="">كل المجلدات</option>${noteFolders().map(x=>`<option ${q.g===x?'selected':''}>${escapeHTML(x)}</option>`).join('')}</select></div>
  <div class="grid g2"><div class="list" id="nList"></div><div class="card" id="nEdit"><div class="muted">اختر ملاحظة للتحرير — حفظ تلقائي + نسخ Versions + ربط [[مشروع]]</div></div></div>`;
  const draw=()=>{const all=Store.col('notes');const s=el.querySelector('#nS').value.trim();
    let arr=all.filter(n=>q.f==='trash'?n.deleted:!n.deleted);
    if(q.g)arr=arr.filter(n=>(n.folder||'')===q.g);
    if(q.f==='fav')arr=arr.filter(n=>n.fav);else if(q.f==='arch')arr=arr.filter(n=>n.archived);else if(TYPES.includes(q.f))arr=arr.filter(n=>n.type===q.f);
    if(s)arr=arr.filter(n=>(n.title+n.body+(n.tags||[]).join(' ')+(n.folder||'')).includes(s));
    el.querySelector('#nList').innerHTML=arr.slice(0,60).map(n=>`<div class="item" data-id="${n.id}"><span>📝 <b>${escapeHTML(n.title||'بلا عنوان')}</b> <span class="pill">${escapeHTML(n.type||'')}</span>${n.folder?` <span class="pill">📁 ${escapeHTML(n.folder)}</span>`:''} ${(n.tags||[]).map(x=>`<span class="tag">${escapeHTML(x)}</span>`).join('')}</span><span class="muted" style="margin-inline-start:auto">${fmtD(n.updatedAt)}</span></div>`).join('')||empty('لا ملاحظات مطابقة — أنشئ أول فكرة 💡');
    el.querySelectorAll('#nList .item').forEach(d=>d.onclick=()=>openEdit(d.dataset.id))};
  const openEdit=id=>{const n=Store.col('notes').find(x=>x.id===id);const box=el.querySelector('#nEdit');
    box.innerHTML=`<label>العنوان</label><input id="eT" value="${escapeHTML(n.title)}"><div class="row"><select id="eTy">${TYPES.map(x=>`<option ${n.type===x?'selected':''}>${x}</option>`).join('')}</select><input id="eFolder" list="nFolders" placeholder="مجلد…" value="${escapeHTML(n.folder||'')}"><datalist id="nFolders">${noteFolders().map(x=>`<option value="${escapeHTML(x)}">`).join('')}</datalist><input id="eTags" placeholder="وسوم بفاصلة" value="${escapeHTML((n.tags||[]).join(','))}"><input id="eProj" placeholder="مرتبطة بمشروع…" value="${escapeHTML(n.project||'')}"></div>
    <label>المحتوى (Markdown + روابط [[عنوان ملاحظة]])</label><textarea id="eB" rows="9">${escapeHTML(n.body||'')}</textarea>
    <div class="row"><button class="btn sm" id="eFav">${n.fav?'★':'☆'}</button><button class="btn sm" id="eArch">أرشيف</button><button class="btn sm danger" id="eDel">${n.deleted?'حذف نهائي':'سلة'}</button><button class="btn sm" id="eVer">Versions (${(n.versions||[]).length})</button><button class="btn sm primary" id="eAI">→ خطة مشروع ✨</button><button class="btn sm" id="eMd">⬇ .md</button><button class="btn sm" id="ePrint">🖨 PDF</button></div>
    <div class="muted" id="ePrev" style="margin-top:8px"></div><div id="eLinks" class="muted"></div><div class="muted">مرفقات: <input type="file" id="eAtt" multiple></div><div id="eAtts">${(n.atts||[]).map(a=>`<span class="pill">${escapeHTML(a)}</span>`).join('')}</div>`;
    const paintLinks=()=>{const links=parseLinks(box.querySelector('#eB').value);const backs=findBacklinks(id);
      box.querySelector('#eLinks').innerHTML=(links.length?`<div>روابط صادرة: ${links.map(l=>`<button class="btn sm" data-go="${escapeHTML(l)}">⛓ ${escapeHTML(l)}</button>`).join(' ')}</div>`:'')+(backs.length?`<div style="margin-top:4px">روابط واردة (${backs.length}): ${backs.map(b=>`<button class="btn sm" data-open="${b.id}">📝 ${escapeHTML(b.title)}</button>`).join(' ')}</div>`:'');
      box.querySelectorAll('#eLinks [data-go]').forEach(b=>b.onclick=()=>{const f=Store.col('notes').find(x=>!x.deleted&&x.title===b.dataset.go);if(f)openEdit(f.id);else toast('لا ملاحظة بهذا العنوان بعد')});
      box.querySelectorAll('#eLinks [data-open]').forEach(b=>b.onclick=()=>openEdit(b.dataset.open))};
    const save=()=>{const nt=box.querySelector('#eT').value,nb=box.querySelector('#eB').value;const vers=[...(n.versions||[])];if(nb!==n.body)vers.unshift({at:new Date().toISOString(),body:n.body||''});
      Store.update('notes',id,{title:nt,body:nb,type:box.querySelector('#eTy').value,folder:box.querySelector('#eFolder').value.trim().slice(0,60),tags:box.querySelector('#eTags').value.split(',').map(x=>x.trim()).filter(Boolean),project:box.querySelector('#eProj').value,versions:vers.slice(0,20)});Store.audit('note_edit',{id});box.querySelector('#ePrev').innerHTML=renderNotePreview(nb);bindPrevLinks();paintLinks();draw()};
    const bindPrevLinks=()=>{box.querySelectorAll('#ePrev [data-link]').forEach(a=>a.onclick=e=>{e.preventDefault();const f=Store.col('notes').find(x=>!x.deleted&&x.title===a.dataset.link);if(f)openEdit(f.id);else toast('لا ملاحظة بهذا العنوان بعد')})};
    let tm;box.querySelector('#eB').oninput=e=>{box.querySelector('#ePrev').innerHTML=renderNotePreview(e.target.value);bindPrevLinks();clearTimeout(tm);tm=setTimeout(save,900)};box.querySelector('#eT').onchange=save;
    box.querySelector('#eFav').onclick=()=>{Store.update('notes',id,{fav:!n.fav});openEdit(id);draw()};
    box.querySelector('#eArch').onclick=()=>{Store.update('notes',id,{archived:!n.archived});draw();openEdit(id)};
    box.querySelector('#eDel').onclick=async()=>{if(n.deleted){if(await confirmDlg('حذف نهائي','لا يمكن التراجع')){Store.remove('notes',id);Store.audit('note_purge',{id});box.innerHTML='';draw()}}else{Store.update('notes',id,{deleted:true});Store.audit('note_trash',{id});draw();box.innerHTML=''}};
    box.querySelector('#eVer').onclick=()=>{box.querySelector('#ePrev').innerHTML=(n.versions||[]).map((v,i)=>`<div class="item">🕓 ${fmtD(v.at)} <button class="btn sm" data-v="${i}">استرجاع</button></div>`).join('')||'لا نسخ';box.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{Store.update('notes',id,{body:n.versions[+b.dataset.v].body});openEdit(id);draw()})};
    box.querySelector('#eAI').onclick=()=>{const body=box.querySelector('#eB').value;const lines=body.split('\n').filter(x=>x.trim()).slice(0,6);const p=Store.push('projects',{name:n.title||'مشروع جديد',desc:'من ملاحظة: '+(n.title||''),stage:'PLANNING',priority:'P2'});lines.forEach((l,i)=>Store.push('tasks',{title:l.replace(/^[-•#*\s]+/,'').slice(0,80),projectId:p.id,priority:'P2',done:false}));Store.audit('ai_note_to_project',{id});toast('حوّلتها إلى مشروع + مهام 🚀');location.hash='#/projects'};
    box.querySelector('#eMd').onclick=()=>{const cur={...n,title:box.querySelector('#eT').value,body:box.querySelector('#eB').value};download((cur.title||'note').replace(/[\\/:*?"<>|]/g,'-').slice(0,60)+'.md',noteToMarkdown(cur),'text/markdown');Store.audit('note_export_md',{id});toast('صُدّرت Markdown ✓')};
    box.querySelector('#ePrint').onclick=()=>{document.body.classList.add('printing-note');box.classList.add('print-area');addEventListener('afterprint',()=>{document.body.classList.remove('printing-note');box.classList.remove('print-area')},{once:true});print()};
    box.querySelector('#ePrev').innerHTML=renderNotePreview(n.body||'');bindPrevLinks();paintLinks();
    box.querySelector('#eAtt').onchange=e=>{const names=[...(n.atts||[]),...[...e.target.files].map(f=>f.name)];Store.update('notes',id,{atts:names});toast('أُرفقت الأسماء (تخزين الملفات في المكتبة)')}};
  el.querySelector('#nNew').onclick=()=>{const n=Store.push('notes',{title:'مشروع التطبيق الجديد',body:'',type:'فكرة',folder:q.g||'',tags:[],project:'',versions:[]});Store.audit('note_create',{id:n.id});draw();openEdit(n.id)};
  el.querySelector('#nS').oninput=e=>{q.s=e.target.value;Store.set('notesQ',q);draw()};el.querySelector('#nF').onchange=e=>{q.f=e.target.value;Store.set('notesQ',q);draw()};el.querySelector('#nG').onchange=e=>{q.g=e.target.value;Store.set('notesQ',q);draw()};draw();
}
