import {Store} from '../store.js';import {escapeHTML} from '../core.js';import {toast,empty,confirmDlg} from '../ui.js';
const STAGES=['IDEA','PLANNING','DEVELOPMENT','TESTING','COMPLETED'];
export function render(el){el.innerHTML=`<div class="between"><h2 style="margin:0">🚀 PROJECT LAB — Kanban</h2><button class="btn primary sm" id="pNew">＋ مشروع</button></div><div class="kanban" id="kb" style="margin-top:12px"></div><div id="pDetail" style="margin-top:12px"></div>`;
  const draw=()=>{const ps=Store.col('projects');
    el.querySelector('#kb').innerHTML=STAGES.map(s=>`<div class="col"><b>${s}</b> <span class="pill">${ps.filter(p=>p.stage===s).length}</span><div class="list" style="margin-top:8px">${ps.filter(p=>p.stage===s).map(p=>`<div class="item" data-id="${p.id}">🚀 <b>${escapeHTML(p.name)}</b><span class="pill">${escapeHTML(p.priority||'')}</span><span style="margin-inline-start:auto" class="row"><button class="btn sm" data-m="l" data-id="${p.id}">◀</button><button class="btn sm" data-m="r" data-id="${p.id}">▶</button></span></div>`).join('')}</div></div>`).join('');
    el.querySelectorAll('.item[data-id]').forEach(d=>d.onclick=e=>{if(e.target.dataset.m)return;detail(d.dataset.id)});
    el.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{const p=ps.find(x=>x.id===b.dataset.id);let i=STAGES.indexOf(p.stage);i=Math.min(4,Math.max(0,i+(b.dataset.m==='r'?1:-1)));Store.update('projects',p.id,{stage:STAGES[i]});Store.audit('project_move',{id:p.id,stage:STAGES[i]});draw()})};
  const detail=id=>{const p=Store.col('projects').find(x=>x.id===id);const tasks=Store.col('tasks').filter(x=>x.projectId===id);const notes=Store.col('notes').filter(n=>!n.deleted&&(n.project||'').includes(p.name)||n.projectId===id);
    el.querySelector('#pDetail').innerHTML=`<div class="card"><div class="between"><h3>📋 ${escapeHTML(p.name)}</h3><button class="btn sm danger" id="pDel">حذف</button></div>
    <div class="muted">${escapeHTML(p.desc||'')}</div><div class="row" style="margin:8px 0"><span class="tag">${escapeHTML(p.stage)}</span><span class="pill">أولوية ${escapeHTML(p.priority||'P2')}</span><span class="pill">${escapeHTML(p.deadline||'بلا موعد')}</span><span class="pill">ميزانية ${escapeHTML(p.budget||'—')}</span></div>
    <label>الوصف/الهدف</label><input id="pD" value="${escapeHTML(p.desc||'')}"><div class="row"><input id="pDl" type="date" value="${escapeHTML(p.deadline||'')}"><input id="pB" placeholder="الميزانية" value="${escapeHTML(p.budget||'')}"><select id="pPr">${['P0','P1','P2','P3'].map(x=>`<option ${p.priority===x?'selected':''}>${x}</option>`).join('')}</select><button class="btn sm primary" id="pS">حفظ</button><button class="btn sm" id="pT">＋ مهمة مرتبطة</button></div>
    <h3>المهام (${tasks.filter(x=>x.done).length}/${tasks.length})</h3><div class="list">${tasks.map(x=>`<div class="item">${x.done?'✅':'⬜'} ${escapeHTML(x.title)}</div>`).join('')||'<div class="muted">لا مهام — أضف أول مهمة</div>'}</div>
    <h3>ملاحظات مرتبطة (${notes.length})</h3><div class="list">${notes.map(n=>`<div class="item">📝 ${escapeHTML(n.title)}</div>`).join('')||'<div class="muted">اكتب "'+escapeHTML(p.name)+'" داخل أي ملاحظة لربطها</div>'}</div></div>`;
    el.querySelector('#pS').onclick=()=>{Store.update('projects',id,{desc:el.querySelector('#pD').value,deadline:el.querySelector('#pDl').value,budget:el.querySelector('#pB').value,priority:el.querySelector('#pPr').value});toast('حُفظ ✓');draw()};
    el.querySelector('#pT').onclick=()=>{const v=prompt('عنوان المهمة:');if(v){Store.push('tasks',{title:v,projectId:id,priority:'P1',done:false});detail(id)}};
    el.querySelector('#pDel').onclick=async()=>{if(await confirmDlg('حذف المشروع','سيبقى في سجل التدقيق')){Store.remove('projects',id);Store.audit('project_delete',{id});el.querySelector('#pDetail').innerHTML='';draw()}}};
  el.querySelector('#pNew').onclick=()=>{const v=prompt('اسم المشروع الجديد:');if(!v)return;const p=Store.push('projects',{name:v.slice(0,80),desc:'',stage:'IDEA',priority:'P2'});Store.audit('project_create',{id:p.id});draw();detail(p.id)};draw();
}
