import {Store} from '../store.js';import {escapeHTML} from '../core.js';import {toast,empty,confirmDlg} from '../ui.js';import {can,myRole} from '../perms.js';
const DEFAULT_STAGES=['IDEA','PLANNING','DEVELOPMENT','TESTING','COMPLETED'];
export const stages=()=>{const s=Store.get('settings',{}).stages;return Array.isArray(s)&&s.length>=2?s:DEFAULT_STAGES};
export const moveStage=(stage,dir)=>{const S=stages();const i=S.indexOf(stage);if(i<0)return S[0];return S[Math.min(S.length-1,Math.max(0,i+dir))]};
export function render(el){el.innerHTML=`<div class="between"><h2 style="margin:0">🚀 PROJECT LAB — Kanban</h2><div class="row"><button class="btn sm" id="pStages">⚙ المراحل</button><button class="btn primary sm" id="pNew">＋ مشروع</button></div></div><div class="kanban" id="kb" style="margin-top:12px"></div><div id="pDetail" style="margin-top:12px"></div>`;
  const draw=()=>{const ps=Store.col('projects');const ST=stages();
    el.querySelector('#kb').innerHTML=ST.map(s=>`<div class="col"><b>${escapeHTML(s)}</b> <span class="pill">${ps.filter(p=>(p.stage||ST[0])===s).length}</span><div class="list" style="margin-top:8px">${ps.filter(p=>(p.stage||ST[0])===s).map(p=>`<div class="item" data-id="${p.id}">🚀 <b>${escapeHTML(p.name)}</b><span class="pill">${escapeHTML(p.priority||'')}</span><span style="margin-inline-start:auto" class="row"><button class="btn sm" data-m="l" data-id="${p.id}">◀</button><button class="btn sm" data-m="r" data-id="${p.id}">▶</button></span></div>`).join('')}</div></div>`).join('');
    el.querySelectorAll('.item[data-id]').forEach(d=>d.onclick=e=>{if(e.target.dataset.m)return;detail(d.dataset.id)});
    el.querySelectorAll('[data-m]').forEach(b=>b.onclick=()=>{const p=ps.find(x=>x.id===b.dataset.id);const ns=moveStage(p.stage||ST[0],b.dataset.m==='r'?1:-1);Store.update('projects',p.id,{stage:ns});Store.audit('project_move',{id:p.id,stage:ns});draw()})};
  el.querySelector('#pStages').onclick=()=>{const v=prompt('المراحل بفاصلة (2+):',stages().join(','));if(v==null)return;
    const arr=v.split(',').map(x=>x.trim().toUpperCase().slice(0,20)).filter(Boolean);
    if(arr.length<2)return toast('مرحلتان على الأقل ⛔');
    const s=Store.get('settings',{});s.stages=arr;Store.set('settings',s);Store.audit('stages_edit',{n:arr.length});draw();toast('حُفظت المراحل ✓')};
  const detail=id=>{const p=Store.col('projects').find(x=>x.id===id);const tasks=Store.col('tasks').filter(x=>x.projectId===id);const notes=Store.col('notes').filter(n=>!n.deleted&&(n.project||'').includes(p.name)||n.projectId===id);
    el.querySelector('#pDetail').innerHTML=`<div class="card"><div class="between"><h3>📋 ${escapeHTML(p.name)}</h3><button class="btn sm danger" id="pDel">حذف</button></div>
    <div class="muted">${escapeHTML(p.desc||'')}</div><div class="row" style="margin:8px 0"><span class="tag">${escapeHTML(p.stage)}</span><span class="pill">أولوية ${escapeHTML(p.priority||'P2')}</span><span class="pill">${escapeHTML(p.deadline||'بلا موعد')}</span><span class="pill">ميزانية ${escapeHTML(p.budget||'—')}</span>${(p.people||'')?`<span class="pill">👥 ${escapeHTML(p.people)}</span>`:''}${(p.links||'')?`<span class="pill">🔗 ${escapeHTML(String(p.links).slice(0,60))}</span>`:''}</div>
    <label>الوصف/الهدف</label><input id="pD" value="${escapeHTML(p.desc||'')}"><div class="row"><input id="pDl" type="date" value="${escapeHTML(p.deadline||'')}"><input id="pB" placeholder="الميزانية" value="${escapeHTML(p.budget||'')}"><select id="pPr">${['P0','P1','P2','P3'].map(x=>`<option ${p.priority===x?'selected':''}>${x}</option>`).join('')}</select></div>
    <div class="row" style="margin-top:8px"><input id="pPeople" placeholder="أشخاص: أحمد، سارة" value="${escapeHTML(p.people||'')}"><input id="pLinks" placeholder="روابط بفاصلة" value="${escapeHTML(p.links||'')}"><button class="btn sm primary" id="pS">حفظ</button><button class="btn sm" id="pT">＋ مهمة مرتبطة</button></div>
    <h3>المهام (${tasks.filter(x=>x.done).length}/${tasks.length})</h3><div class="list">${tasks.map(x=>`<div class="item">${x.done?'✅':'⬜'} ${escapeHTML(x.title)}</div>`).join('')||'<div class="muted">لا مهام — أضف أول مهمة</div>'}</div>
    <h3>ملاحظات مرتبطة (${notes.length})</h3><div class="list">${notes.map(n=>`<div class="item">📝 ${escapeHTML(n.title)}</div>`).join('')||'<div class="muted">اكتب "'+escapeHTML(p.name)+'" داخل أي ملاحظة لربطها</div>'}</div></div>`;
    el.querySelector('#pS').onclick=()=>{Store.update('projects',id,{desc:el.querySelector('#pD').value,deadline:el.querySelector('#pDl').value,budget:el.querySelector('#pB').value,priority:el.querySelector('#pPr').value,people:el.querySelector('#pPeople').value.slice(0,200),links:el.querySelector('#pLinks').value.slice(0,500)});toast('حُفظ ✓');draw()};
    el.querySelector('#pT').onclick=()=>{const v=prompt('عنوان المهمة:');if(!v)return;const p=Store.push('tasks',{title:v,projectId:id,priority:'P1',done:false});detail(id)};
    el.querySelector('#pDel').onclick=async()=>{if(!can(myRole(),'delete'))return toast('صلاحية غير كافية ⛔');if(await confirmDlg('حذف المشروع','سيبقى في سجل التدقيق')){Store.remove('projects',id);Store.audit('project_delete',{id});el.querySelector('#pDetail').innerHTML='';draw()}}};
  el.querySelector('#pNew').onclick=()=>{const v=prompt('اسم المشروع الجديد:');if(!v)return;const p=Store.push('projects',{name:v.slice(0,80),desc:'',stage:stages()[0],priority:'P2'});Store.audit('project_create',{id:p.id});draw();detail(p.id)};draw();
}
